export type Seg = string | { gold: string };
export type Lang = 'en' | 'pt' | 'fr';

export const RESUME_URL = 'assets/angelo-scholze-resume.pdf';
export const EMAIL = 'antonioscholze@gmail.com';
export const NAME = 'Angelo Scholze';

export type Content = {
  nav: { href: string; label: string }[];
  hero: { role: string; sub: Seg[] };
  stats: { k: string; v: string; gilt: boolean }[];
  about: Seg[];
  experience: { name: string; dates: string; body: Seg[] }[];
  skills: string[];
  contact: { k: string; label: string; href?: string; external?: boolean }[];
  ui: { download: string; downloadPdf: string; emailMe: string; getInTouch: string };
};

const skillList = (yr: string) => [
  `Flutter — 7${yr}`,
  `Dart — 7${yr}`,
  `Git — 7${yr}`,
  `SOLID — 6${yr}`,
  `Clean Code — 5${yr}`,
  `BloC — 5${yr}`,
  `AppStore Admin — 4${yr}`,
  `Provider — 3${yr}`,
  `GetX — 3${yr}`,
  `Firebase — 3${yr}`,
  `JavaScript — 2${yr}`,
  `MongoDB — 2${yr}`,
  `Kotlin — 1${yr}`,
  `TDD — 1${yr}`,
  'React',
  'Next.js',
  'Node.js',
  'PostgreSQL',
];

const contactRows = (k: { email: string; phone: string; linkedin: string; github: string }) => [
  { k: k.email, label: EMAIL, href: `mailto:${EMAIL}` },
  { k: k.phone, label: '+55 41 99676-6899' },
  {
    k: k.linkedin,
    label: '/in/angelo-scholze',
    href: 'https://www.linkedin.com/in/angelo-scholze/',
    external: true,
  },
  {
    k: k.github,
    label: '/AngeloAntonioScholze',
    href: 'https://github.com/AngeloAntonioScholze',
    external: true,
  },
];

const en: Content = {
  nav: [
    { href: '#about', label: './about' },
    { href: '#experience', label: './experience' },
    { href: '#skills', label: './skills' },
    { href: '#contact', label: './contact' },
  ],
  hero: {
    role: 'Full Stack Senior Flutter Developer',
    sub: [
      'I am a Senior-Level Software Developer with ',
      { gold: 'seven years' },
      ' of experience, specializing primarily in mobile development using the ',
      { gold: 'Flutter' },
      ' framework, paired with full-stack work in ',
      { gold: 'React' },
      ', ',
      { gold: 'Next.js' },
      ' and ',
      { gold: 'Node.js' },
      '.',
    ],
  },
  stats: [
    { k: 'years_experience', v: '7', gilt: true },
    { k: 'companies', v: '5', gilt: false },
    { k: 'core_stack', v: 'Flutter', gilt: false },
    { k: 'languages', v: 'EN / PT / FR', gilt: false },
  ],
  about: [
    'Seven years building mobile-first products in ',
    { gold: 'Flutter' },
    ' — ',
    { gold: 'BloC' },
    ', ',
    { gold: 'GetX' },
    ', ',
    { gold: 'MobX' },
    ', ',
    { gold: 'Provider' },
    ' — paired with full-stack range across ',
    { gold: 'React' },
    ', ',
    { gold: 'Next.js' },
    ' and ',
    { gold: 'Node.js/Express' },
    '. Conversations and documentation entirely in English. Comfortable owning architecture end to end: ',
    { gold: 'REST APIs' },
    ', ',
    { gold: 'MongoDB/PostgreSQL' },
    ', ',
    { gold: 'SOLID' },
    ' principles, ',
    { gold: 'Clean Code' },
    ' and ',
    { gold: 'TDD' },
    ', ',
    { gold: 'Scrum' },
    ' delivery. Also freelancing full-stack work on Fiverr since 2021. Portuguese native, English fluent, French basic.',
  ],
  experience: [
    {
      name: 'leading-edge-ag-solutions/',
      dates: 'Aug 2025 — current',
      body: [
        'Senior Software Developer, ',
        { gold: 'Flutter' },
        '. From-scratch to market development; complex web delivery using ',
        { gold: 'Flutter' },
        ' for full-stack; built with ',
        { gold: 'MobX' },
        ' and Modular libraries, ',
        { gold: 'SOLID' },
        ' principles and Clean Code.',
      ],
    },
    {
      name: 'ulist/',
      dates: 'Aug 2023 — Aug 2025',
      body: [
        'Senior Software Developer, ',
        { gold: 'Flutter' },
        '. Refactored and implemented the app UI; developed using ',
        { gold: 'MobX' },
        ' and Modular libraries with ',
        { gold: 'SOLID' },
        ' and Clean Code practices.',
      ],
    },
    {
      name: 'meta/',
      dates: 'Mar 2023 — Aug 2023',
      body: [
        'Software Developer, ',
        { gold: 'Flutter' },
        '. Built a data-crawling script and urban-mobility features with ',
        { gold: 'Google Maps' },
        ' and ',
        { gold: 'Waze' },
        ' deep-linking; new ',
        { gold: 'BloC' },
        ' state architecture over ',
        { gold: 'REST APIs' },
        ' and ',
        { gold: 'PostgreSQL' },
        '.',
      ],
    },
    {
      name: 'ibf/',
      dates: 'Aug 2021 — Nov 2021',
      body: [
        'Full Stack Developer. Development in ',
        { gold: 'React' },
        ', ',
        { gold: 'Next.js' },
        ' and ',
        { gold: 'Node.js' },
        ' using ',
        { gold: 'SOLID' },
        ' principles and Clean Code; integration and development of ',
        { gold: 'REST APIs' },
        ' and webhooks.',
      ],
    },
    {
      name: 'wayv-tecnologia/',
      dates: 'Nov 2021 — Feb 2023',
      body: [
        'Software Developer, ',
        { gold: 'Flutter' },
        '. Migrated Flutter 1 to Flutter 3, built new ',
        { gold: 'BloC' },
        '/',
        { gold: 'GetX' },
        ' state architecture, integrated ',
        { gold: 'REST APIs' },
        ' and ',
        { gold: 'MongoDB' },
        ' under Scrum.',
      ],
    },
  ],
  skills: skillList('y'),
  contact: contactRows({ email: 'email', phone: 'phone', linkedin: 'linkedin', github: 'github' }),
  ui: {
    download: 'download resume',
    downloadPdf: 'download resume.pdf',
    emailMe: 'email me',
    getInTouch: 'Get in touch',
  },
};

const pt: Content = {
  nav: [
    { href: '#about', label: './sobre' },
    { href: '#experience', label: './experiencia' },
    { href: '#skills', label: './habilidades' },
    { href: '#contact', label: './contato' },
  ],
  hero: {
    role: 'Desenvolvedor Flutter Sênior Full Stack',
    sub: [
      'Sou Desenvolvedor de Software Sênior com ',
      { gold: 'sete anos' },
      ' de experiência, especializado principalmente em desenvolvimento mobile com o framework ',
      { gold: 'Flutter' },
      ', somado a trabalho full-stack em ',
      { gold: 'React' },
      ', ',
      { gold: 'Next.js' },
      ' e ',
      { gold: 'Node.js' },
      '.',
    ],
  },
  stats: [
    { k: 'anos_experiencia', v: '7', gilt: true },
    { k: 'empresas', v: '5', gilt: false },
    { k: 'stack_principal', v: 'Flutter', gilt: false },
    { k: 'idiomas', v: 'EN / PT / FR', gilt: false },
  ],
  about: [
    'Sete anos construindo produtos mobile-first em ',
    { gold: 'Flutter' },
    ' — ',
    { gold: 'BloC' },
    ', ',
    { gold: 'GetX' },
    ', ',
    { gold: 'MobX' },
    ', ',
    { gold: 'Provider' },
    ' — somados a alcance full-stack em ',
    { gold: 'React' },
    ', ',
    { gold: 'Next.js' },
    ' e ',
    { gold: 'Node.js/Express' },
    '. Conversas e documentação inteiramente em inglês. Confortável assumindo a arquitetura de ponta a ponta: ',
    { gold: 'REST APIs' },
    ', ',
    { gold: 'MongoDB/PostgreSQL' },
    ', princípios ',
    { gold: 'SOLID' },
    ', ',
    { gold: 'Clean Code' },
    ' e ',
    { gold: 'TDD' },
    ', entregas em ',
    { gold: 'Scrum' },
    '. Também trabalho freelance full-stack no Fiverr desde 2021. Português nativo, inglês fluente, francês básico.',
  ],
  experience: [
    {
      name: 'leading-edge-ag-solutions/',
      dates: 'Ago 2025 — atual',
      body: [
        'Desenvolvedor de Software Sênior, ',
        { gold: 'Flutter' },
        '. Desenvolvimento do zero até o mercado; entrega web complexa usando ',
        { gold: 'Flutter' },
        ' em full-stack; construído com as bibliotecas ',
        { gold: 'MobX' },
        ' e Modular, princípios ',
        { gold: 'SOLID' },
        ' e Clean Code.',
      ],
    },
    {
      name: 'ulist/',
      dates: 'Ago 2023 — Ago 2025',
      body: [
        'Desenvolvedor de Software Sênior, ',
        { gold: 'Flutter' },
        '. Refatoração e implementação da UI do app; desenvolvimento com as bibliotecas ',
        { gold: 'MobX' },
        ' e Modular, com práticas ',
        { gold: 'SOLID' },
        ' e Clean Code.',
      ],
    },
    {
      name: 'meta/',
      dates: 'Mar 2023 — Ago 2023',
      body: [
        'Desenvolvedor de Software, ',
        { gold: 'Flutter' },
        '. Script de coleta de dados e funcionalidades de mobilidade urbana com deep-linking do ',
        { gold: 'Google Maps' },
        ' e ',
        { gold: 'Waze' },
        '; nova arquitetura de estado ',
        { gold: 'BloC' },
        ' sobre ',
        { gold: 'REST APIs' },
        ' e ',
        { gold: 'PostgreSQL' },
        '.',
      ],
    },
    {
      name: 'ibf/',
      dates: 'Ago 2021 — Nov 2021',
      body: [
        'Desenvolvedor Full Stack. Desenvolvimento em ',
        { gold: 'React' },
        ', ',
        { gold: 'Next.js' },
        ' e ',
        { gold: 'Node.js' },
        ' com princípios ',
        { gold: 'SOLID' },
        ' e Clean Code; integração e desenvolvimento de ',
        { gold: 'REST APIs' },
        ' e webhooks.',
      ],
    },
    {
      name: 'wayv-tecnologia/',
      dates: 'Nov 2021 — Fev 2023',
      body: [
        'Desenvolvedor de Software, ',
        { gold: 'Flutter' },
        '. Migração de Flutter 1 para Flutter 3, nova arquitetura de estado ',
        { gold: 'BloC' },
        '/',
        { gold: 'GetX' },
        ', integração de ',
        { gold: 'REST APIs' },
        ' e ',
        { gold: 'MongoDB' },
        ' sob Scrum.',
      ],
    },
  ],
  skills: skillList('a'),
  contact: contactRows({
    email: 'email',
    phone: 'telefone',
    linkedin: 'linkedin',
    github: 'github',
  }),
  ui: {
    download: 'baixar curriculo',
    downloadPdf: 'baixar curriculo.pdf',
    emailMe: 'me enviar email',
    getInTouch: 'Entre em contato',
  },
};

const fr: Content = {
  nav: [
    { href: '#about', label: './apropos' },
    { href: '#experience', label: './experience' },
    { href: '#skills', label: './competences' },
    { href: '#contact', label: './contact' },
  ],
  hero: {
    role: 'Développeur Flutter Senior Full Stack',
    sub: [
      'Je suis développeur logiciel senior avec ',
      { gold: 'sept ans' },
      " d'expérience, spécialisé principalement en développement mobile avec le framework ",
      { gold: 'Flutter' },
      ', complété par du travail full-stack en ',
      { gold: 'React' },
      ', ',
      { gold: 'Next.js' },
      ' et ',
      { gold: 'Node.js' },
      '.',
    ],
  },
  stats: [
    { k: 'annees_experience', v: '7', gilt: true },
    { k: 'entreprises', v: '5', gilt: false },
    { k: 'stack_principale', v: 'Flutter', gilt: false },
    { k: 'langues', v: 'EN / PT / FR', gilt: false },
  ],
  about: [
    'Sept ans à construire des produits mobile-first en ',
    { gold: 'Flutter' },
    ' — ',
    { gold: 'BloC' },
    ', ',
    { gold: 'GetX' },
    ', ',
    { gold: 'MobX' },
    ', ',
    { gold: 'Provider' },
    ' — complétés par une portée full-stack sur ',
    { gold: 'React' },
    ', ',
    { gold: 'Next.js' },
    ' et ',
    { gold: 'Node.js/Express' },
    ". Échanges et documentation entièrement en anglais. À l'aise pour porter l'architecture de bout en bout : ",
    { gold: 'REST APIs' },
    ', ',
    { gold: 'MongoDB/PostgreSQL' },
    ', principes ',
    { gold: 'SOLID' },
    ', ',
    { gold: 'Clean Code' },
    ' et ',
    { gold: 'TDD' },
    ', livraison en ',
    { gold: 'Scrum' },
    '. Également freelance full-stack sur Fiverr depuis 2021. Portugais natif, anglais courant, français basique.',
  ],
  experience: [
    {
      name: 'leading-edge-ag-solutions/',
      dates: 'Août 2025 — actuel',
      body: [
        'Développeur logiciel senior, ',
        { gold: 'Flutter' },
        ". Développement de zéro jusqu'au marché ; livraison web complexe avec ",
        { gold: 'Flutter' },
        ' en full-stack ; construit avec les bibliothèques ',
        { gold: 'MobX' },
        ' et Modular, principes ',
        { gold: 'SOLID' },
        ' et Clean Code.',
      ],
    },
    {
      name: 'ulist/',
      dates: 'Août 2023 — Août 2025',
      body: [
        'Développeur logiciel senior, ',
        { gold: 'Flutter' },
        ". Refonte et implémentation de l'UI de l'app ; développement avec les bibliothèques ",
        { gold: 'MobX' },
        ' et Modular, pratiques ',
        { gold: 'SOLID' },
        ' et Clean Code.',
      ],
    },
    {
      name: 'meta/',
      dates: 'Mars 2023 — Août 2023',
      body: [
        'Développeur logiciel, ',
        { gold: 'Flutter' },
        '. Script de collecte de données et fonctionnalités de mobilité urbaine avec deep-linking ',
        { gold: 'Google Maps' },
        ' et ',
        { gold: 'Waze' },
        " ; nouvelle architecture d'état ",
        { gold: 'BloC' },
        ' sur ',
        { gold: 'REST APIs' },
        ' et ',
        { gold: 'PostgreSQL' },
        '.',
      ],
    },
    {
      name: 'ibf/',
      dates: 'Août 2021 — Nov 2021',
      body: [
        'Développeur full stack. Développement en ',
        { gold: 'React' },
        ', ',
        { gold: 'Next.js' },
        ' et ',
        { gold: 'Node.js' },
        ' avec principes ',
        { gold: 'SOLID' },
        ' et Clean Code ; intégration et développement de ',
        { gold: 'REST APIs' },
        ' et webhooks.',
      ],
    },
    {
      name: 'wayv-tecnologia/',
      dates: 'Nov 2021 — Févr 2023',
      body: [
        'Développeur logiciel, ',
        { gold: 'Flutter' },
        ". Migration de Flutter 1 vers Flutter 3, nouvelle architecture d'état ",
        { gold: 'BloC' },
        '/',
        { gold: 'GetX' },
        ', intégration de ',
        { gold: 'REST APIs' },
        ' et ',
        { gold: 'MongoDB' },
        ' en Scrum.',
      ],
    },
  ],
  skills: skillList('a'),
  contact: contactRows({
    email: 'email',
    phone: 'telephone',
    linkedin: 'linkedin',
    github: 'github',
  }),
  ui: {
    download: 'telecharger cv',
    downloadPdf: 'telecharger cv.pdf',
    emailMe: 'me contacter',
    getInTouch: 'Me contacter',
  },
};

export const content: Record<Lang, Content> = { en, pt, fr };
